/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ERouteImport } from './routes/e'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EIndexRouteImport } from './routes/e/index'
import { Route as ESessionIdIndexRouteImport } from './routes/e/$sessionId/index'

const ERoute = ERouteImport.update({
  id: '/e',
  path: '/e',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EIndexRoute = EIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ERoute,
} as any)
const ESessionIdIndexRoute = ESessionIdIndexRouteImport.update({
  id: '/$sessionId/',
  path: '/$sessionId/',
  getParentRoute: () => ERoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e': typeof ERouteWithChildren
  '/e/': typeof EIndexRoute
  '/e/$sessionId/': typeof ESessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e': typeof EIndexRoute
  '/e/$sessionId': typeof ESessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e': typeof ERouteWithChildren
  '/e/': typeof EIndexRoute
  '/e/$sessionId/': typeof ESessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e' | '/e/' | '/e/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e' | '/e/$sessionId'
  id: '__root__' | '/' | '/e' | '/e/' | '/e/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ERoute: typeof ERouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/e': {
      id: '/e'
      path: '/e'
      fullPath: '/e'
      preLoaderRoute: typeof ERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/': {
      id: '/e/'
      path: '/'
      fullPath: '/e/'
      preLoaderRoute: typeof EIndexRouteImport
      parentRoute: typeof ERoute
    }
    '/e/$sessionId/': {
      id: '/e/$sessionId/'
      path: '/$sessionId'
      fullPath: '/e/$sessionId/'
      preLoaderRoute: typeof ESessionIdIndexRouteImport
      parentRoute: typeof ERoute
    }
  }
}

interface ERouteChildren {
  EIndexRoute: typeof EIndexRoute
  ESessionIdIndexRoute: typeof ESessionIdIndexRoute
}

const ERouteChildren: ERouteChildren = {
  EIndexRoute: EIndexRoute,
  ESessionIdIndexRoute: ESessionIdIndexRoute,
}

const ERouteWithChildren = ERoute._addFileChildren(ERouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ERoute: ERouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
