/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EIndexRouteImport } from './routes/e/index'
import { Route as ESessionIdRouteImport } from './routes/e/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EIndexRoute = EIndexRouteImport.update({
  id: '/e/',
  path: '/e/',
  getParentRoute: () => rootRouteImport,
} as any)
const ESessionIdRoute = ESessionIdRouteImport.update({
  id: '/e/$sessionId',
  path: '/e/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e/$sessionId': typeof ESessionIdRoute
  '/e/': typeof EIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e/$sessionId': typeof ESessionIdRoute
  '/e': typeof EIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e/$sessionId': typeof ESessionIdRoute
  '/e/': typeof EIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e/$sessionId' | '/e/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e/$sessionId' | '/e'
  id: '__root__' | '/' | '/e/$sessionId' | '/e/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ESessionIdRoute: typeof ESessionIdRoute
  EIndexRoute: typeof EIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/': {
      id: '/e/'
      path: '/e'
      fullPath: '/e/'
      preLoaderRoute: typeof EIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$sessionId': {
      id: '/e/$sessionId'
      path: '/e/$sessionId'
      fullPath: '/e/$sessionId'
      preLoaderRoute: typeof ESessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ESessionIdRoute: ESessionIdRoute,
  EIndexRoute: EIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
