/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorERouteImport } from './routes/_editor/e'
import { Route as EditorEIndexRouteImport } from './routes/_editor/e/index'
import { Route as EditorESessionIdIndexRouteImport } from './routes/_editor/e/$sessionId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorERoute = EditorERouteImport.update({
  id: '/_editor/e',
  path: '/e',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorEIndexRoute = EditorEIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorERoute,
} as any)
const EditorESessionIdIndexRoute = EditorESessionIdIndexRouteImport.update({
  id: '/$sessionId/',
  path: '/$sessionId/',
  getParentRoute: () => EditorERoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e': typeof EditorERouteWithChildren
  '/e/': typeof EditorEIndexRoute
  '/e/$sessionId/': typeof EditorESessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e': typeof EditorEIndexRoute
  '/e/$sessionId': typeof EditorESessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_editor/e': typeof EditorERouteWithChildren
  '/_editor/e/': typeof EditorEIndexRoute
  '/_editor/e/$sessionId/': typeof EditorESessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e' | '/e/' | '/e/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e' | '/e/$sessionId'
  id: '__root__' | '/' | '/_editor/e' | '/_editor/e/' | '/_editor/e/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorERoute: typeof EditorERouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_editor/e': {
      id: '/_editor/e'
      path: '/e'
      fullPath: '/e'
      preLoaderRoute: typeof EditorERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_editor/e/': {
      id: '/_editor/e/'
      path: '/'
      fullPath: '/e/'
      preLoaderRoute: typeof EditorEIndexRouteImport
      parentRoute: typeof EditorERoute
    }
    '/_editor/e/$sessionId/': {
      id: '/_editor/e/$sessionId/'
      path: '/$sessionId'
      fullPath: '/e/$sessionId/'
      preLoaderRoute: typeof EditorESessionIdIndexRouteImport
      parentRoute: typeof EditorERoute
    }
  }
}

interface EditorERouteChildren {
  EditorEIndexRoute: typeof EditorEIndexRoute
  EditorESessionIdIndexRoute: typeof EditorESessionIdIndexRoute
}

const EditorERouteChildren: EditorERouteChildren = {
  EditorEIndexRoute: EditorEIndexRoute,
  EditorESessionIdIndexRoute: EditorESessionIdIndexRoute,
}

const EditorERouteWithChildren =
  EditorERoute._addFileChildren(EditorERouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorERoute: EditorERouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
